### ISSUE TITLE
Questions on signed and unsigned transaction from offchain workers

### ISSUE THREAD

**Issue by jimmychu0807** [jimmychu0807/substrate-offchain-pricefetch#1]
Refer to the src: https://github.com/jimmychu0807/substrate-offchain-pricefetch/blob/still-good/node/runtime/src/offchaincb.rs#L120-L128

The example is based off from Ben's callback example. If there is an offchain request, the offchain worker will send both a signed and unsigned transaction back onchain.

I run the node in `dev` mode. I expect this makes Alice, Bob,... keys accessible in the runtime.

Questions

1. For signed tx, I first used polkadot-JS app and made a sudo call to `add_authority()` with Alice key. But in calling `offchain_signed()`, `authority_id()` function still return `None`. I suspect the `local_keys` are empty. How could I add Alice key in the `local_keys`?

As a side question, can I print out what `local_keys` is in the terminal?
@gnunicorn 🙏

2. For unsigned tx, I implemented `validate_unsigned()`, basically copying the core from [`im-online/src/lib.rs`](https://github.com/paritytech/substrate/blob/jimmy/base/srml/im-online/src/lib.rs#L495-L538), with the returning `ValidTransaction` `provides` parameter includes nothing versus to `(current_session, authority_id).encode()` in `im-online/src/lib.rs`. It still returns Extrinsic invalid message for me. 
@tomusdrw 🙏

---

Detail output from terminal

```
2019-11-26 13:49:10 Idle (0 peers), best: #6 (0xb42f…62b7), finalized #5 (0xa5ea…3613), ⬇ 0 ⬆ 0
2019-11-26 13:49:12 Starting consensus session on top of parent 0xb42f5068b947b861666759c38ce87e568885b82af49cbf5519dae6ccd45b62b7
pinging
2019-11-26 13:49:12 Prepared block for proposing at 7 [hash: 0xaf0d152aae662639af94ae68cea39264d53f27ce1fa7dc930f80f566e72b45c5; parent_hash: 0xb42f…62b7; extrinsics: [0x122a…d4fd, 0x0f21…d0d6]]
2019-11-26 13:49:12 Pre-sealed block for proposal at 7. Hash now 0x7280ccf5a62ade19131fc81b311d97acc7b93dec1f6d84254166b3a13b449db5, previously 0xaf0d152aae662639af94ae68cea39264d53f27ce1fa7dc930f80f566e72b45c5.
pinging
2019-11-26 13:49:12 Imported #7 (0x7280…9db5)
offchain_worker
offchain_unsigned
2019-11-26 13:49:12 Submitting to the pool: 0308020b (isSigned: None)
authority not found
2019-11-26 13:49:12 Extrinsic invalid: 0x6bb01bd687515f3b69884c2693d33629b2e332aa449e1c7f352fddc7e2204474
```

**Comment by jimmychu0807** [comment]
Ben reply:

But is that true? The docs of my offchain callback, unfortunately, misses that little code block that makes the dev key accessible to the offchain keystore. Do you have that?

https://github.com/gnunicorn/substrate-offchain-cb/blob/master/src/service.rs#L112

**Comment by tomusdrw** [comment]
The keystore stores public keys, but they are separated using `KEY_TYPE`. So the fact that you have Alice's seed phrase for BABE, doesn't mean that your custom key type is also in the keystore (even if you expect it to be exactly the same type).
You create a custom app-crypto wrapper here:
https://github.com/jimmychu0807/substrate-offchain-pricefetch/blob/still-good/node/runtime/src/lib.rs#L244
and later use it for transaction submission.

This means that the "dev" key (for the specific `KEY_TYPE`) needs to be inserted manually either during CLI initialisation or via RPC.

**Comment by tomusdrw** [comment]
Re 2:
Did you register your `ValidateUnsigned` like so:
https://github.com/paritytech/substrate/blob/df94d9043b435482371c57ed81954e11686cb351/bin/node/runtime/src/lib.rs#L528
?

**Comment by jimmychu0807** [comment]
@tomusdrw: Thanks. I am able to send unsigned txs.

@gnunicorn: Indeed, I need to add the dev_keys in order to sign transaction. Thank you.
