### ISSUE TITLE
Mysterious unused import warnings

### ISSUE THREAD

**Issue by JoshOrndorff** [jimmychu0807/substrate-offchain-pricefetch#7]
The compiler gives `unused import` warnings about several traits.

```
warning: unused imports: `offchain::SignAndSubmitTransaction`, `offchain::SubmitSignedTransaction`
  --> runtime/src/price_fetch.rs:16:3
   |
16 |   offchain::SubmitSignedTransaction,
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17 |   offchain::SubmitUnsignedTransaction,
18 |   offchain::SignAndSubmitTransaction };
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

```

```
warning: unused import: `num_traits::float::FloatCore`
  --> runtime/src/price_fetch.rs:25:5
   |
25 | use num_traits::float::FloatCore;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

However all of these traits are actually used. Removing any one of them will create a compile _error_. At first this seemed related to https://github.com/rust-lang/rust/issues/45268 but that issue is always about using modules, so I'm not sure it's the same.

**Comment by jimmychu0807** [comment]
Same thought. I do use those methods, yet being called by Rust as unused.

**Comment by JoshOrndorff** [comment]
Yeah, it's definitely a rust issue. Feel free to close; it's your repo afterall :)

**Comment by tomusdrw** [comment]
Are you sure that usage of those methods does not depend on the features? Like some of them being used only for `std` compilation?

**Comment by JoshOrndorff** [comment]
On riot Robin said:

> Not sure but whenever I use only the methods and not the name of a trait I always import is as _:
use foo::bar::MyTrait as _; maybe Rust compiler enforces this now? I would be surprised though. Also what often happens is that some things are unused for some subset of crate features.

I tried the `_` trick, and it did *not* solve the warnings, so I guess it most likely is related to features as @tomusdrw also suggested.

However this resulted in the same error message as if I removed the imports entirely
```rust
#[cfg(feature = "std")]
use system::offchain::{
    SubmitSignedTransaction,
    SubmitUnsignedTransaction,
    SignAndSubmitTransaction
};
```

**Comment by tomusdrw** [comment]
Looking at the code it seems that only `SubmitUnsignedTransaction` is actually required:
https://github.com/jimmychu0807/substrate-offchain-pricefetch/blob/master/node/runtime/src/price_fetch.rs#L268

And that's exactly what the warnings says. Have you tried reducing the import to:
```
use system::offchain::SubmitUnsignedTransaction;
```
?

Regarding `FloatCore` it indeed seems unnecessary what exact line you get error at?

**Comment by jimmychu0807** [comment]
yea, I am mid-way experimenting with both signed unsigned txs, and related APIs.

**Comment by JoshOrndorff** [comment]
This is what happens when you remove the FloatCore import.

```
error[E0599]: no method named `round` found for type `f64` in the current scope
   --> /home/joshorndorff/remote-builds/offchain-node/runtime/src/price_fetch.rs:290:43
    |
290 |     let val_u64: u64 = (val_f64 * 10000.).round() as u64;
    |                                           ^^^^^ method not found in `f64`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use num_traits::float::FloatCore;`

error[E0599]: no method named `round` found for type `f64` in the current scope
   --> /home/joshorndorff/remote-builds/offchain-node/runtime/src/price_fetch.rs:314:38
    |
314 |     let val_u64 = (val_f64 * 10000.).round() as u64;
    |                                      ^^^^^ method not found in `f64`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use num_traits::float::FloatCore;`

error[E0599]: no method named `round` found for type `f64` in the current scope
   --> /home/joshorndorff/remote-builds/offchain-node/runtime/src/price_fetch.rs:328:58
    |
328 |     let price_avg: u64 = (price_sum as f64 / amt as f64).round() as u64;
    |                                                          ^^^^^ method not found in `f64`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use num_traits::float::FloatCore;`
```

**Comment by tomusdrw** [comment]
Hmm interesting. The method is defintiely there: https://doc.rust-lang.org/std/primitive.f64.html#method.round, but most likely `FloatCore` is needed only for non-std environment then.

**Comment by JoshOrndorff** [comment]
> `FloatCore` is needed only for non-std environment then.

Indeed. Thank you for your help and patience while finding this error.
https://github.com/jimmychu0807/substrate-offchain-pricefetch/pull/13
